puts "test1.rb"
puts "lalala"
print "mimimi"
puts "editing this now"
puts "editing for third time"
puts "creating a conflict hehe"
puts "this is cris. why are you messing?"
puts "haha. bet you can't push yet. :)"
